version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/*
      - ./app:/app
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile 
    volumes:
      - ./app:/app
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'someword'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'firsttest'
    volumes:
      - mysqldata:/var/lib/mysql 
    ports:                                                      
      - 3306:3306
volumes:
  mysqldata: {}